# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 497)
        MainWindow.setStyleSheet("background:\'black\';")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_list = QtWidgets.QListWidget(self.centralwidget)
        self.image_list.setGeometry(QtCore.QRect(10, 50, 121, 421))
        self.image_list.setStyleSheet("background:\'orange\';")
        self.image_list.setObjectName("image_list")
        self.papka_button = QtWidgets.QPushButton(self.centralwidget)
        self.papka_button.setGeometry(QtCore.QRect(20, 20, 101, 23))
        self.papka_button.setStyleSheet("background:\'orange\';\n"
"border-radius:10px")
        self.papka_button.setObjectName("papka_button")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(140, 20, 531, 411))
        self.image_label.setStyleSheet("color:white;\n"
"")
        self.image_label.setObjectName("image_label")
        self.left_button = QtWidgets.QPushButton(self.centralwidget)
        self.left_button.setGeometry(QtCore.QRect(140, 450, 101, 23))
        self.left_button.setStyleSheet("background:\'orange\';\n"
"border-radius:10px")
        self.left_button.setObjectName("left_button")
        self.right_button = QtWidgets.QPushButton(self.centralwidget)
        self.right_button.setGeometry(QtCore.QRect(250, 450, 101, 23))
        self.right_button.setStyleSheet("background:\'orange\';\n"
"border-radius:10px")
        self.right_button.setObjectName("right_button")
        self.mirror_button = QtWidgets.QPushButton(self.centralwidget)
        self.mirror_button.setGeometry(QtCore.QRect(360, 450, 101, 23))
        self.mirror_button.setStyleSheet("background:\'orange\';\n"
"border-radius:10px")
        self.mirror_button.setObjectName("mirror_button")
        self.sharpness_button = QtWidgets.QPushButton(self.centralwidget)
        self.sharpness_button.setGeometry(QtCore.QRect(470, 450, 101, 23))
        self.sharpness_button.setStyleSheet("background:\'orange\';\n"
"border-radius:10px")
        self.sharpness_button.setObjectName("sharpness_button")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(580, 450, 101, 23))
        self.pushButton_6.setStyleSheet("background:\'orange\';\n"
"border-radius:10px")
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.papka_button.setText(_translate("MainWindow", "Папка"))
        self.image_label.setText(_translate("MainWindow", "Картинка"))
        self.left_button.setText(_translate("MainWindow", "Ліворуч"))
        self.right_button.setText(_translate("MainWindow", "Праворуч"))
        self.mirror_button.setText(_translate("MainWindow", "Дзеркало"))
        self.sharpness_button.setText(_translate("MainWindow", "Ріскість"))
        self.pushButton_6.setText(_translate("MainWindow", "Чорно Білий"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
